// This acts as our temporary database for search and counts
export const calculators = [

  // Finance Calculators

  { name: 'SIP Calculator with Inflation', path: '/calculator/finance/sip', category: 'finance' },
  { name: 'EMI Calculator', path: '/calculator/finance/emi', category: 'finance' },
  { name: 'FD Calculator', path: '/calculator/finance/fd', category: 'finance' },
  { name: 'Home Loan Calculator', path: '/calculator/finance/home-loan', category: 'finance' },
  { name: 'Personal Loan Calculator', path: '/calculator/finance/personal-loan', category: 'finance' },
  { name: 'RD Calculator', path: '/calculator/finance/rd', category: 'finance' },
  { name: 'Lumpsum Calculator', path: '/calculator/finance/lumpsum', category: 'finance' },
  { name: 'PPF Calculator', path: '/calculator/finance/ppf', category: 'finance' },
  { name: 'GST Calculator', path: '/calculator/finance/gst', category: 'finance' },
  { name: 'Simple Interest Calculator', path: '/calculator/finance/simple-interest', category: 'finance' },
  { name: 'Compound Interest Calculator', path: '/calculator/finance/compound-interest', category: 'finance' },
  { name: 'Retirement Planning Calculator', path: '/calculator/finance/retirement', category: 'finance' },
  { name: 'Gratuity Calculator', path: '/calculator/finance/gratuity', category: 'finance' },
  { name: 'Car Loan Calculator', path: '/calculator/finance/car-loan', category: 'finance' },
  { name: 'Income Tax Calculator (New Regime)', path: '/calculator/finance/income-tax', category: 'finance' },
  { name: 'Salary Calculator', path: '/calculator/finance/salary', category: 'finance' },
  { name: 'Take Home Salary Calculator', path: '/calculator/finance/take-home-salary', category: 'finance' },
  { name: 'HRA Calculator', path: '/calculator/finance/hra', category: 'finance' },
  { name: 'PF Calculator', path: '/calculator/finance/pf', category: 'finance' },
  { name: 'EPF Interest Calculator', path: '/calculator/finance/epf-interest', category: 'finance' },
  { name: 'NPS Calculator', path: '/calculator/finance/nps', category: 'finance' },
  { name: 'ELSS Calculator', path: '/calculator/finance/elss', category: 'finance' },
  { name: 'Mutual Fund Returns Calculator', path: '/calculator/finance/mutual-fund-returns', category: 'finance' },
  { name: 'Stock Profit Calculator', path: '/calculator/finance/stock-profit', category: 'finance' },
  { name: 'Brokerage Calculator', path: '/calculator/finance/brokerage', category: 'finance' },
  { name: 'Break Even Calculator', path: '/calculator/finance/break-even', category: 'finance' },
  { name: 'Margin Calculator', path: '/calculator/finance/margin', category: 'finance' },
  { name: 'LTV Calculator', path: '/calculator/finance/ltv', category: 'finance' },
  { name: 'Credit Card EMI Calculator', path: '/calculator/finance/cc-emi', category: 'finance' },
  { name: 'Loan Affordability Calculator', path: '/calculator/finance/loan-affordability', category: 'finance' },
  { name: 'Business Loan EMI Calculator', path: '/calculator/finance/business-loan', category: 'finance' },
  { name: 'Education Loan EMI Calculator', path: '/calculator/finance/education-loan', category: 'finance' },
  { name: 'Gold Loan Calculator', path: '/calculator/finance/gold-loan', category: 'finance' },

  //Health Calculators
  { name: 'BMI Calculator', path: '/calculator/health/bmi', category: 'health' },
  { name: 'BMR Calculator', path: '/calculator/health/bmr', category: 'health' },
  { name: 'Body Fat Precentage Calculator', path: '/calculator/health/body-fat', category: 'health' },
  { name: 'Calorie Calculator', path: '/calculator/health/calorie', category: 'health' },
  { name: 'Calories Burned Calculator', path: '/calculator/health/calories-burned', category: 'health' },
  { name: 'Pregnancy Calculator', path: '/calculator/health/pregnancy', category: 'health' },
  { name: 'Macro Calculator', path: '/calculator/health/macros', category: 'health' },
  { name: 'Water Intake Calculator', path: '/calculator/health/water-intake', category: 'health' },
  { name: 'Ideal Weight Calculator', path: '/calculator/health/ideal-weight', category: 'health' },
  { name: 'TDEE Calculator', path: '/calculator/health/tdee', category: 'health' },
  { name: 'Period & Menstrual Cycle Calculator', path: '/calculator/health/period-cycle', category: 'health' },

  //Math Calculators
  { name: 'Percentage Calculator', path: '/calculator/math/percentage', category: 'math' },
  { name: 'Fraction Calculator', path: '/calculator/math/fraction', category: 'math' },
  { name: 'Scientific Calculator', path: '/calculator/math/scientific', category: 'math' },
  { name: 'LCM Calculator', path: '/calculator/math/lcm', category: 'math' },
  { name: 'Standard Deviation Calculator', path: '/calculator/math/standard-deviation', category: 'math' },
  { name: 'Quadratic Formula Calculator', path: '/calculator/math/quadratic', category: 'math' },
  { name: 'Mean Median Mode Calculator', path: '/calculator/math/mean-median-mode', category: 'math' },
  { name: 'Area & Perimeter Calculator', path: '/calculator/math/area-perimeter', category: 'math' },
  { name: 'Volume & Surface Area Calculator', path: '/calculator/math/volume-surface-area', category: 'math' },
  { name: 'Pythagorean Theorem Calculator', path: '/calculator/math/pythagorean', category: 'math' },
  { name: 'Log Calculator (Logarithm) Calculator', path: '/calculator/math/logarithm', category: 'math' },
  { name: 'Exponent Calculator', path: '/calculator/math/exponent', category: 'math' },
  { name: 'Matrix Calculator', path: '/calculator/math/matrix', category: 'math' },
  { name: 'Probability Calculator', path: '/calculator/math/probability', category: 'math' },
  { name: 'Percentage Increase & Decrease Calculator', path: '/calculator/math/percentage-inc-dec', category: 'math' },
  { name: 'Ratio Calculator', path: '/calculator/math/ratio', category: 'math' },
  { name: 'Proportion Calculator', path: '/calculator/math/proportion', category: 'math' },
  { name: 'Profit, Loss & Discount Calculator', path: '/calculator/math/profitloss', category: 'math' },
  { name: 'Algebra Calculator', path: '/calculator/math/algebra', category: 'math' },
  { name: 'Permutation and Combination Calculator', path: '/calculator/math/permutation-combination', category: 'math' },
  { name: 'Average Calculator', path: '/calculator/math/average', category: 'math' },

  // Conversion Calculators
  { name: 'Unit Converter', path: '/calculator/conversion/unit', category: 'conversion' },
  { name: 'Weight Converter', path: '/calculator/conversion/weight', category: 'conversion' },
  { name: 'Temperature Converter', path: '/calculator/conversion/temperature', category: 'conversion' },
  { name: 'Volume & Capacity Converter', path: '/calculator/conversion/volume', category: 'conversion' },
  { name: 'Area Converter', path: '/calculator/conversion/area', category: 'conversion' },
  { name: 'Time Converter', path: '/calculator/conversion/time', category: 'conversion' },
  { name: 'Cooking Measurement Converter', path: '/calculator/conversion/cooking', category: 'conversion' },
  { name: 'Speed Converter', path: '/calculator/conversion/speed', category: 'conversion' },
  { name: 'Digital Storage Converter', path: '/calculator/conversion/digital-storage', category: 'conversion' },
  { name: 'Data Transfer & Network Speed Converter', path: '/calculator/conversion/data-transfer', category: 'conversion' },
  { name: 'Fraction & Decimal Converter', path: '/calculator/conversion/fraction-decimal', category: 'conversion' },
  { name: 'Number Base Converter', path: '/calculator/conversion/number-base', category: 'conversion' },
  { name: 'Roman Numeral Converter', path: '/calculator/conversion/roman', category: 'conversion' },
  { name: 'Pressure Converter', path: '/calculator/conversion/pressure', category: 'conversion' },
  { name: 'Power Converter', path: '/calculator/conversion/power', category: 'conversion' },
  { name: 'Energy Converter', path: '/calculator/conversion/energy', category: 'conversion' },
  { name: 'Angle Converter', path: '/calculator/conversion/angle', category: 'conversion' },
  { name: 'Torque Converter', path: '/calculator/conversion/torque', category: 'conversion' },

  // Everyday Utility Calculators

  { name: 'Age Calculator', path: '/calculator/everyday/age', category: 'everyday' },
  { name: 'Grocery Price Calculator', path: '/calculator/everyday/grocery-price', category: 'everyday' },
  { name: 'Fuel Cost & Mileage Calculator', path: '/calculator/everyday/mileage', category: 'everyday' },
  { name: 'Electricity Bill Calculator', path: '/calculator/everyday/electricity', category: 'everyday' },
  { name: 'Discount Calculator', path: '/calculator/everyday/discount', category: 'everyday' },
  { name: 'Date Calculator', path: '/calculator/everyday/date', category: 'everyday' },
  { name: 'Time Calculator', path: '/calculator/everyday/time-duration', category: 'everyday' },
  { name: 'Basic Calculator', path: '/calculator/everyday/basic-calculator', category: 'everyday' },
  { name: 'Monthly Expense Calculator', path: '/calculator/everyday/expense', category: 'everyday' },



  //Education Calculators
  { name: 'CGPA to Percentage Calculator', path: '/calculator/education/cgpa', category: 'education' },
  { name: 'SGPA to CGPA Calculator', path: '/calculator/education/cgpa-sgpa', category: 'education' },
  { name: 'Attendance Calculator', path: '/calculator/education/attendance', category: 'education' },
  { name: 'Education Loan Calculator', path: '/calculator/education/education-loan', category: 'education' },
  { name: 'Typing Speed Calculator (WPM)', path: '/calculator/education/typing', category: 'education' },
  { name: 'Typing Speed Test', path: '/calculator/education/typing-test', category: 'education' },
  { name: 'Word & Character Counter', path: '/calculator/education/word-counter', category: 'education' },
  { name: 'Marks Percentage Calculator', path: '/calculator/education/marks-percentage', category: 'education' },
  { name: 'Time & Work Calculator', path: '/calculator/education/time-work', category: 'education' },
  { name: 'GATE Score Calculator', path: '/calculator/education/gate-score', category: 'education' },
  { name: 'Study Plan Calculator', path: '/calculator/education/study-plan', category: 'education' },
  { name: 'NEET Rank Predictor', path: '/calculator/education/neet-rank', category: 'education' },

  //Construction Calculators
  { name: 'Concrete Calculator', path: '/calculator/construction/concrete', category: 'construction' },
  { name: 'Partition and Framing Calculator', path: '/calculator/construction/framing-stud', category: 'construction' },
  { name: 'Brick Calculator', path: '/calculator/construction/brick', category: 'construction' },
  { name: 'AAC Block & Adhesive Calculator', path: '/calculator/construction/aac-block', category: 'construction' },
  { name: 'Plastering Material Calculator', path: '/calculator/construction/plastering', category: 'construction' },
  { name: 'Wall Putty & Primer Calculator', path: '/calculator/construction/putty-primer', category: 'construction' },
  { name: 'Brass Volume Calculator (Sand & Aggregate)', path: '/calculator/construction/brass-volume', category: 'construction' },
  { name: 'Concrete Mix Calculator (Cement, Sand, Aggregate)', path: '/calculator/construction/concrete-mix', category: 'construction' },
  { name: 'TMT Steel Bar (Sariya) Weight Calculator', path: '/calculator/construction/tmt-steel-weight', category: 'construction' },
  { name: 'Roof Slab Concrete & Steel Estimator', path: '/calculator/construction/roof-slab-estimator', category: 'construction' },
  { name: 'Column & Footing Concrete Calculator', path: '/calculator/construction/column-footing', category: 'construction' },
  { name: 'Earthwork & Excavation Calculator (Soil Volume)', path: '/calculator/construction/earthwork-excavation', category: 'construction' },
  { name: 'Water Tank Capacity Calculator', path: '/calculator/construction/water-tank-capacity', category: 'construction' },
  { name: 'Tile Calculator (Floor & Wall)', path: '/calculator/construction/tile', category: 'construction' },
  { name: 'Marble & Granite Flooring Estimator', path: '/calculator/construction/marble-granite', category: 'construction' },
  { name: 'Paint Calculator', path: '/calculator/construction/paint', category: 'construction' },
  { name: 'False Ceiling & POP Calculator', path: '/calculator/construction/false-ceiling', category: 'construction' },
  { name: 'Plywood & Sunmica (Laminate) Calculator', path: '/calculator/construction/plywood', category: 'construction' },
  { name: 'Gaj to Square Feet / Sq Meter Converter', path: '/calculator/construction/gaj-converter', category: 'construction' },
  { name: 'Cent, Guntha & Bigha Land Converter', path: '/calculator/construction/regional-land', category: 'construction' },
  { name: 'House Construction Cost Estimator', path: '/calculator/construction/construction-cost', category: 'construction' },
  { name: 'Staircase Step & Concrete Calculator', path: '/calculator/construction/staircase-step', category: 'construction' },

  //Engineering Calculators
  { name: ' Ohm\'s Law & Power Calculator', path: '/calculator/engineering/ohms-law-power', category: 'engineering' },
  { name: 'Capacitor Calculator', path: '/calculator/engineering/capacitor', category: 'engineering' },
  { name: 'Torque Calculator', path: '/calculator/engineering/torque', category: 'engineering' },
  { name: 'Stress & Strain Calculator', path: '/calculator/engineering/stress-strain', category: 'engineering' },
  { name: 'Beam Deflection Calculator', path: '/calculator/engineering/beam-deflection', category: 'engineering' },
  { name: 'Concrete Volume Calculator', path: '/calculator/engineering/concrete-volume', category: 'engineering' },
  { name: 'Structural Load Calculator', path: '/calculator/engineering/structural-load', category: 'engineering' },

  { name: 'Reynolds Number Calculator (Fluid Mechanics)', path: '/calculator/engineering/fluid-mechanics-reynolds', category: 'engineering' },
  { name: 'Ideal Gas Law Calculator (Thermodynamics)', path: '/calculator/engineering/thermodynamics-ideal-gas', category: 'engineering' },
  { name: 'Electrical Power Loss & Voltage Drop Calculator', path: '/calculator/engineering/electrical-power-loss', category: 'engineering' },
  { name: 'RC Circuit Calculator', path: '/calculator/engineering/rc-circuit', category: 'engineering' },
  { name: 'Frequency & Wavelength Calculator', path: '/calculator/engineering/frequency-wavelength', category: 'engineering' },
  { name: 'Gear Ratio & RPM Calculator (Mechanical)', path: '/calculator/engineering/gear-ratio-speed', category: 'engineering' },
  { name: 'Transformer Turns Ratio Calculator', path: '/calculator/engineering/transformer-turns-ratio', category: 'engineering' },
  { name: 'Belt Length & Pulley Speed Calculator', path: '/calculator/engineering/belt-length-pulley-speed', category: 'engineering' },

  // { name: 'Age Calculator', path: '/calculator/utility/age', category: 'utility' },
  // { name: 'Currency Converter', path: '/calculator/conversion/currency', category: 'conversion' },
  // { name: 'CGPA Calculator', path: '/calculator/education/cgpa', category: 'education' },
  // { name: 'Margin Calculator', path: '/calculator/business/margin', category: 'business' },
  // { name: 'Ohm Law Calculator', path: '/calculator/engineering/ohm', category: 'engineering' },
];

export const getCategoryCount = (categoryId) => {
  return calculators.filter(calc => calc.category === categoryId).length;
};